name: Infracost

on: [pull_request] 
  
jobs:

  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    env:
      TF_ROOT: "."
    
    steps:

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate infracost cost estimate baseline
        id: payload
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v2

      - name: Generate Infracost diff
        run: |
          infracost diff --path=${TF_ROOT} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
      
      - name: Post Infracost comment 
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=update  \
                                     --policy-path=.github/workflows/infracost-policy.rego
      - name: Slack output
        run: |
            infracost output --path /tmp/infracost.json --format slack-message --out-file /tmp/slack.json
 
      - name: Slack send message
        run: |
          curl -X POST -H "Content-type: application/json" -d @/tmp/slack.json ${{ secrets.SLACK_WEBHOOK_URL }}