name: Terraform Test with localstack

on:
  push:
    branches-ignore:
      - "main"

jobs:

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run terraform validate
        run: |
          terraform -chdir=tests init
          terraform -chdir=tests validate

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      
      - name: Start Localstack
        run: |
   
          python3 -m pip install localstack awscli-local pyOpenSSL cryptography
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStack startup..."
          localstack wait -t 60
          docker ps -a 
          echo "Startup Complete"
      
      - name: Run Terraform Plan
        run: |
          terraform -chdir=tests init
          terraform -chdir=tests plan
      
      - name: Run Terraform apply
        run: |
          terraform -chdir=tests init
          terraform -chdir=tests apply -auto-approve

  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    env:
      TF_ROOT: "."
    
    steps:

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      
      - name: Checkout base branch
        uses: actions/checkout@v2

      - name: Generate infracost cost estimate baseline
        run: |
          infracost breakdown --path=${TF_ROOT} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v2

      - name: Generate Infracost diff
        run: |
          infracost diff --path=${TF_ROOT} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
      
      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --behavior=update
   
